INSERT INTO breed (name) VALUES ('beagle')
INSERT INTO breed (name) VALUES ('havanese')
INSERT INTO breed (name) VALUES ('pug')
INSERT INTO breed (name) VALUES ('rottweiler')

INSERT INTO dog (name, breed_id, img_url) VALUES ('rose',1,'https://images.dog.ceo/breeds/beagle/n02088364_11391.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('fant',1,'https://images.dog.ceo/breeds/beagle/n02088364_6109.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('tommy',1,'https://images.dog.ceo/breeds/beagle/n02088364_17473.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('sissi',2,'https://images.dog.ceo/breeds/havanese/00100trPORTRAIT_00100_BURST20191103202017556_COVER.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('bob',2,'https://images.dog.ceo/breeds/havanese/00100trPORTRAIT_00100_BURST20191222103956878_COVER.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('pat',3,'https://images.dog.ceo/breeds/pug/n02110958_13597.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('george',3,'https://images.dog.ceo/breeds/pug/n02110958_3338.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('spike',3,'https://images.dog.ceo/breeds/pug/n02110958_3644.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('lassie',4,'https://images.dog.ceo/breeds/rottweiler/n02106550_13213.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('kåre',4,'https://images.dog.ceo/breeds/rottweiler/n02106550_8887.jpg')
INSERT INTO dog (name, breed_id, img_url) VALUES ('janne',4,'https://images.dog.ceo/breeds/rottweiler/n02106550_6926.jpg')

INSERT INTO skill (name) VALUES ('housetrained')
INSERT INTO skill (name) VALUES ('basic-obedience')

INSERT INTO dog_skill (dog_id, skill_id) VALUES (1,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (3,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (4,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (5,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (6,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (8,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (9,1)

INSERT INTO dog_skill (dog_id, skill_id) VALUES (1,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (3,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (4,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (6,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (7,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (9,2)