INSERT INTO dog (name,breed) VALUES ('tomy','affenpinscher')
INSERT INTO dog (name,breed) VALUES ('pat','akita')
INSERT INTO dog (name,breed) VALUES ('fant','boxer')
INSERT INTO dog (name,breed) VALUES ('sissi','boxer')
INSERT INTO dog (name,breed) VALUES ('george','bouvier')
INSERT INTO dog (name,breed) VALUES ('rose','eskimo')
INSERT INTO dog (name,breed) VALUES ('spike','rottweiler')
INSERT INTO dog (name,breed) VALUES ('tommy','rottweiler')
INSERT INTO dog (name,breed) VALUES ('lassie','tervuren')
INSERT INTO dog (name,breed) VALUES ('bob','stbernard')
INSERT INTO dog (name,breed) VALUES ('vizsla','vizsla')
INSERT INTO dog (name,breed) VALUES ('janne','vizsla')

INSERT INTO skill (name) VALUES ('housetrained')
INSERT INTO skill (name) VALUES ('basic-obedience')

INSERT INTO dog_skill (dog_id, skill_id) VALUES (1,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (2,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (3,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (4,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (5,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (6,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (8,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (9,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (10,1)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (12,1)

INSERT INTO dog_skill (dog_id, skill_id) VALUES (1,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (3,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (4,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (6,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (7,2)
INSERT INTO dog_skill (dog_id, skill_id) VALUES (9,2)